name: CI-Test

on: 
  pull_request:
    branches: ['**']

  push:
    branches: [main]
      
defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || !contains(toJSON(github.event.pull_request.labels.*.name), 'ci-skip')"
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: './package-lock.json'

      - name: Setup npm registry authentication
        run: |
          npm config set @theSportsDev:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test
        env:
          NODE_ENV: test
          CI: true

